### ISSUE TITLE
AttributeError: 'BertModel' object has no attribute 'weights'

### ISSUE THREAD

**Issue by seollyul** [TashinAhmed/HATE#1]
When I try to run the following code it occur an error:

![螢幕擷取畫面 2024-04-15 200540](https://github.com/TashinAhmed/HATE/assets/167062016/63844f11-0135-47a1-a510-b0f17fa21ef0)

![螢幕擷取畫面 2024-04-15 200818](https://github.com/TashinAhmed/HATE/assets/167062016/b4b7504a-6fa4-4175-9648-cfc24efaa0e6)

How can I solve the problem?

**Comment by TashinAhmed** [comment]
Hi @seollyul  

What version of transformers are you using? As **weights** under **BertModel** might get deprecated in newer version of transformers. I tested our model on `transformers==2.11.0`.

Attaching `requirements.txt` file in **main** branch.

Let me know whether it worked or not.

**Comment by seollyul** [comment]
Hi @TashinAhmed 
Thanks for your reply.

I have changed the version but still got this error:
![not_define](https://github.com/TashinAhmed/HATE/assets/167062016/cd4d79cf-de85-46ea-bc44-1439c1c33e5f)
May I ask what is  the input "transformer_layer"  here ?

**Comment by TashinAhmed** [comment]
@seollyul 

Can you please create a separate issue for this one?
