### ISSUE TITLE
NameError: name 'transformer_layer' is not defined

### ISSUE THREAD

**Issue by seollyul** [TashinAhmed/HATE#2]
I have got the following error:

![transformer_Layer_not difine](https://github.com/TashinAhmed/HATE/assets/167062016/abfc3858-5010-452c-81de-33eb15ba66ff)

I thought it is because the input 'transformer_layer' here is not define.

May I ask how to solve the problem?

**Comment by TashinAhmed** [comment]
@seollyul 
Sorry for the trouble, 
add these few lines under strategy.scope,

```
with strategy.scope():
    transformer_layer = transformers.TFDistilBertModel.\
    from_pretrained('distilbert-base-multilingual-cased')
    # Rest of the code
```

**Comment by seollyul** [comment]
@TashinAhmed 
I added the code and it worked. 
Thank you very much.╰(*°▽°*)╯

**Comment by TashinAhmed** [comment]
@seollyul 
You are welcome. Can you please mark my previous reply as the correct answer so that a new visitor can directly find the solution instead of other comments!
